# numpy.array 基础

In [2]:
import numpy

In [4]:
numpy.__version__

'1.15.4'

In [5]:
import numpy as np

In [6]:
np.__version__

'1.15.4'

## python list的特点

In [8]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L[5]

5

In [10]:
 L[5]="Machine Learning"

In [11]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [12]:
import array

In [14]:
arr=array.array('i',[i for i in range(10)])

In [15]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]=100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [18]:
arr[5]="Machine"

TypeError: an integer is required (got type str)

# numpy.array

In [23]:
nparr=np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
nparr[5]

5

In [25]:
nparr[5]=100

In [26]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [27]:
nparr.dtype

dtype('int64')

In [28]:
nparr[5]=5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int64')

# 其他创建numpy.array的方法

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(10).dtype

dtype('float64')

In [34]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arrange

In [42]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
[i for i in range(0,20,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linespace

In [49]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [50]:
np.random.randint(0,10)

2

In [51]:
np.random.randint(0,10,10)

array([8, 8, 6, 4, 7, 5, 1, 3, 2, 1])

In [52]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.random.randint(4,8,size=10)

array([6, 6, 6, 4, 4, 7, 7, 4, 4, 5])

In [55]:
np.random.randint(4,8,size=(3,5))

array([[6, 4, 7, 6, 5],
       [5, 7, 5, 6, 6],
       [4, 4, 5, 5, 7]])

In [59]:
np.random.seed(666)

In [60]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [62]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [63]:
np.random.random()

0.2811684913927954

In [64]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [65]:
np.random.random()

0.7674123439764099

In [66]:
np.random.random(10)

array([0.95323137, 0.29097383, 0.84778197, 0.3497619 , 0.92389692,
       0.29489453, 0.52438061, 0.94253896, 0.07473949, 0.27646251])

In [67]:
np.random.seed(666)
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])

In [68]:
np.random.random((3,5))

array([[0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811],
       [0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959]])

In [69]:
np.random.normal()

0.028016723832884196

In [72]:
np.random.normal(10,100)

-144.98470081020176

In [73]:
np.random.normal(0,1,(3,5))

array([[ 0.72946452, -0.32695477,  1.14133677,  0.45243662, -2.23496877],
       [ 1.27047766, -0.72928821,  1.35925255, -1.20990266, -0.04618272],
       [-0.44118244,  0.46953431,  0.44325817, -1.66738875, -1.81731749]])

In [75]:
np.random.normal?

In [76]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

# NUMPY.array的基本操作

In [77]:
import numpy as np

In [78]:
x=np.arange(10)

In [79]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
X=np.arange(15).reshape(3,5)

In [81]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [83]:
x.ndim

1

In [84]:
X.ndim

2

In [85]:
x.shape

(10,)

In [86]:
X.shape

(3, 5)

In [87]:
x.size

10

In [88]:
X.size

15

## numpy.array 的数据访问

In [89]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x[0]

0

In [91]:
x[-1]

9

In [93]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
X[(0,0)]

0

In [95]:
X[2,2]

12

In [96]:
x[0:5]

array([0, 1, 2, 3, 4])

In [97]:
x[5:]

array([5, 6, 7, 8, 9])

In [100]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [101]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [102]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [104]:
X[0,:]

array([0, 1, 2, 3, 4])

In [105]:
X[0,:].ndim

1

In [108]:
subX=X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [111]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [112]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [114]:
subX=X[:2,:3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [115]:
X[0,0]=0
subX

array([[100,   1,   2],
       [  5,   6,   7]])

## reshape

In [116]:
x.shape

(10,)

In [117]:
x.ndim

1

In [118]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
A=x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
B=x.reshape(1,10)

In [123]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [124]:
B.ndim

2

In [125]:
B.shape

(1, 10)

In [126]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [128]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [129]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
x.reshape(3,-1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)