# 索引

In [1]:
import numpy as np
x=np.random.normal(0,1,size=1000000)

In [2]:
np.min(x)

-5.160570489802835

In [3]:
np.argmin(x)

949863

In [4]:
x[949863]

-5.160570489802835

In [5]:
np.argmax(x)

939785

In [6]:
x[939785]

4.982941360727488

In [7]:
np.max(x)

4.982941360727488

# 排序

In [8]:
x=np.arange(16)

In [9]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)

In [11]:
x

array([ 8, 13,  9,  2, 10,  3,  7,  6, 11,  1, 15,  4, 14,  0,  5, 12])

In [12]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
x

array([ 8, 13,  9,  2, 10,  3,  7,  6, 11,  1, 15,  4, 14,  0,  5, 12])

In [16]:
x.sort()

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X= np.random.randint(10,size=(4,4))

In [19]:
X

array([[8, 3, 1, 3],
       [0, 0, 5, 2],
       [8, 5, 9, 4],
       [8, 9, 3, 7]])

In [20]:
np.sort(X)

array([[1, 3, 3, 8],
       [0, 0, 2, 5],
       [4, 5, 8, 9],
       [3, 7, 8, 9]])

In [21]:
np.sort(X,axis=1)

array([[1, 3, 3, 8],
       [0, 0, 2, 5],
       [4, 5, 8, 9],
       [3, 7, 8, 9]])

In [22]:
np.sort(X,axis=0)

array([[0, 0, 1, 2],
       [8, 3, 3, 3],
       [8, 5, 5, 4],
       [8, 9, 9, 7]])

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.random.shuffle(x)

In [25]:
x

array([ 2,  9,  5, 13,  8,  6, 11,  3,  7, 14,  4, 12,  1, 10, 15,  0])

In [26]:
np.argsort(x)

array([15, 12,  0,  7, 10,  2,  5,  8,  4,  1, 13,  6, 11,  3,  9, 14])

In [27]:
x[15]

0

In [28]:
np.partition(x,3)

array([ 1,  0,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 10, 13, 15, 14])

In [29]:
np.argpartition(x,3)

array([12, 15,  0,  7, 10,  2,  5,  8,  4,  1,  6, 11, 13,  3, 14,  9])

In [30]:
X

array([[8, 3, 1, 3],
       [0, 0, 5, 2],
       [8, 5, 9, 4],
       [8, 9, 3, 7]])

In [31]:
np.argsort(X)

array([[2, 1, 3, 0],
       [0, 1, 3, 2],
       [3, 1, 0, 2],
       [2, 3, 0, 1]])

In [32]:
np.argsort(X,axis=0)

array([[1, 1, 0, 1],
       [0, 0, 3, 0],
       [2, 2, 1, 2],
       [3, 3, 2, 3]])

In [33]:
np.argpartition(X,2)

array([[2, 1, 3, 0],
       [0, 1, 3, 2],
       [3, 1, 0, 2],
       [2, 3, 0, 1]])

In [34]:
np.argpartition(X,2,axis=0)

array([[1, 1, 0, 1],
       [0, 0, 3, 0],
       [2, 2, 1, 2],
       [3, 3, 2, 3]])

# Fancy Indexing

In [35]:
x=np.arange(16)

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x[3]

3

In [38]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [39]:
x[3:9:2]

array([3, 5, 7])

In [40]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [41]:
ind=[3,5,8]

In [42]:
x[ind]

array([3, 5, 8])

In [44]:
ind = np.array([[0,2],[1,3]])

In [46]:
x[ind]

array([[0, 2],
       [1, 3]])

In [49]:
X=np.arange(16).reshape(4,-1)

In [50]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
row=np.array([0,1,2])

In [52]:
cow=np.array([1,2,3])

In [53]:
X[row,cow]

array([ 1,  6, 11])

In [54]:
X[0,cow]

array([1, 2, 3])

In [55]:
X[:2,cow]

array([[1, 2, 3],
       [5, 6, 7]])

In [56]:
col=[True,False,True,True]

In [57]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

# numpy.array的比较

In [58]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [60]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [61]:
x<=3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [62]:
x>=3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [63]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [64]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [65]:
2*x==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [66]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [68]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
np.sum(x<=3)

4

In [72]:
np.count_nonzero(x<=3)

4

In [76]:
np.any(x<0)

False

In [75]:
np.all(x>=0)

True

In [77]:
np.sum(X%2==0)

8

In [78]:
np.sum(X%2==0,axis=1)

array([2, 2, 2, 2])

In [79]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [82]:
np.sum((x>3)&(x<10))

6

In [83]:
np.sum((x%2==0)|(x>10))

11

In [85]:
np.sum(~(x==0))

15

In [86]:
x[x<5]

array([0, 1, 2, 3, 4])

In [87]:
x[~(x==0)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
x[(x%2==0)]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [89]:
X[X[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

Pandas