In [1]:
from sklearn import datasets

In [3]:
images=datasets.load_sample_images()

In [4]:
images.keys()

dict_keys(['images', 'filenames', 'DESCR'])

In [5]:
print(images.DESCR)

Image: china.jpg
Released under a creative commons license. [1]
Attribution: Some rights reserved by danielbuechele [2]
Retrieved 21st August, 2011 from [3] by Robert Layton

[1] http://creativecommons.org/licenses/by/2.0/
[2] http://www.flickr.com/photos/danielbuechele/
[3] http://www.flickr.com/photos/danielbuechele/6061409035/sizes/z/in/photostream/


Image: flower.jpg
Released under a creative commons license. [1]
Attribution: Some rights reserved by danielbuechele [2]
Retrieved 21st August, 2011 from [3] by Robert Layton

[1] http://creativecommons.org/licenses/by/2.0/
[2] http://www.flickr.com/photos/vultilion/
[3] http://www.flickr.com/photos/vultilion/6056698931/sizes/z/in/photostream/






In [7]:
bostom=datasets.load_boston()

In [11]:
bostom.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [12]:
X_train=bostom.data

In [13]:
y_train=bostom.target

In [14]:
X_train.shape

(506, 13)

In [15]:
y_train.shape

(506,)

In [16]:
import numpy as np

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
standardScaler=StandardScaler()

In [20]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
X_train=standardScaler.transform(X_train)

In [22]:
X_train[:2,:]

array([[-0.41978194,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
         0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
        -1.45900038,  0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, -0.27259857, -0.74026221,
         0.19427445,  0.36716642,  0.55715988, -0.8678825 , -0.98732948,
        -0.30309415,  0.44105193, -0.49243937]])

In [23]:
X_train=bostom.data

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(bostom.data,bostom.target,test_size=0.2,random_state=666)

In [52]:
X_train = standardScaler.transform(X_train)
X_test_standard = standardScaler.transform(X_test)

In [55]:
X_train[:3,:]

array([[ -0.46893015,  -0.41194551,  -1.74879661,  -1.34690855,
        -15.96199604,  -9.10697042,  -2.48569884,  -1.00812379,
         -1.14471176,  -2.42870094,  -8.92982078,  -3.90586605,
         -1.88195221],
       [ -0.41833086,  -0.5086552 ,  -1.47671633,  -1.34690855,
          2.69319052,  -9.62859107,  -2.41817164,  -2.01274449,
         -0.90682587,  -2.41554334,  -8.16021611,  -3.95093426,
         -1.68526883],
       [ -0.45883418,  -0.5086552 ,  -1.68876012,  -1.34690855,
         -6.03743679,  -9.55146428,  -2.4219653 ,  -1.69945161,
         -1.17114352,  -2.42820709,  -7.98919285,  -3.90708625,
         -1.73399758]])

In [56]:
y_train

array([23.2, 19. , 17.5, 26.4, 20.2, 21.5, 21.2, 19.4, 38.7, 21.4, 23.1,
       10.9, 20.1, 29.6, 13.6, 11.5, 33.4, 16. , 24.3, 23.2, 21. ,  6.3,
        8.3, 32. , 13.1, 23.9, 16.5, 14.9, 13.9, 26.4, 23.7, 36.2, 42.8,
       32.7, 25. , 33.4, 36.2, 32.2, 25. , 14.4, 35.1, 20.1, 24. , 24.7,
       21.4, 19.1, 15.4, 31.5, 17.6, 26.6, 22. , 12.7,  8.8, 13.3, 24.3,
       20. , 19.8, 16.4, 24.8, 21.2, 10.4, 21.2, 19.2, 30.7, 27.1, 23.3,
       22.2, 27. , 18.2, 17.7, 19.8,  7.4, 22.4, 18.1, 18.6, 10.5, 20. ,
       19.9, 23.5, 23.1, 19.3, 24.7, 21.6, 48.3, 11.7, 41.7, 14.3, 21.5,
       13.6, 13.8, 20.4, 18.5, 37.6, 23.7, 17.3, 16.5, 31.6, 16.2, 24.3,
       34.9, 19.5, 17.1, 27.5, 50. , 23.1, 36. , 50. , 22. , 22. , 17.1,
       23. , 18.5, 24.1, 21.4,  9.6, 13.3, 22.8, 21.9, 19.4, 21.6, 23.8,
       21.7, 11.3,  7.5, 24.4, 28.1, 17.5, 20.7, 39.8, 12.8,  7.2, 50. ,
       13.4, 44.8, 15.3, 21.7, 18.2, 14.9, 34.6, 22.9, 25. , 20.1, 34.9,
       35.2, 22.2, 19.4, 21.9,  8.8, 13.1, 28.7, 44

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf=KNeighborsClassifier(n_neighbors=3)

In [28]:
knn_clf.fit(X_train,y_train)

ValueError: Unknown label type: 'continuous'

In [29]:
X_test_standard.shape

(102, 13)

In [30]:
y_test.shape

(102,)

In [50]:
y_test.astype(int)

array([23, 17, 22, 37, 25, 19, 16, 18, 29, 18,  8, 24, 19, 15, 22, 23, 26,
       15, 12, 28, 37,  8,  7, 46, 26, 19, 24, 15, 37, 33, 43,  7, 24, 22,
       19, 20, 31, 30, 21, 13, 24, 11, 24, 20, 23, 10, 23, 33, 22, 19, 22,
       32, 15, 20, 20, 20, 17, 19, 17, 14, 19, 23, 24, 14, 15, 12, 22, 22,
       17, 25,  5, 31, 19, 23, 45, 18,  7, 23, 19, 35, 28, 23,  9, 29, 32,
       17, 18, 27, 17, 50, 19, 33, 24, 37, 18, 14, 22, 22, 13, 17, 18, 10])

In [32]:
from sklearn import utils

In [45]:
print(utils.multiclass.type_of_target(y_test))

continuous


In [38]:
print(utils.multiclass.type_of_target(y_test.astype('int')))

multiclass


In [39]:
y_test

array([23.9, 17.8, 22.1, 37.3, 25. , 19.7, 16.2, 18.9, 29.6, 18.4,  8.4,
       24.7, 19.8, 15.4, 22.2, 23.3, 26.6, 15.6, 12.6, 28.4, 37. ,  8.3,
        7.2, 46.7, 26.5, 19.4, 24.5, 15.6, 37.9, 33. , 43.5,  7. , 24.8,
       22.5, 19.4, 20.3, 31. , 30.1, 21. , 13.5, 24.4, 11.9, 24.5, 20.8,
       23.7, 10.8, 23.7, 33.1, 22.9, 19.1, 22.3, 32. , 15. , 20.3, 20.6,
       20.4, 17.2, 19.9, 17.8, 14.5, 19.6, 23.9, 24. , 14.2, 15.2, 12. ,
       22. , 22.6, 17.4, 25. ,  5. , 31.7, 19.6, 23.2, 45.4, 18.9,  7.2,
       23.1, 19.5, 35.4, 28.2, 23.4,  9.7, 29.9, 32.9, 17. , 18.9, 27.5,
       17.5, 50. , 19.1, 33.3, 24.4, 37.2, 18.8, 14.5, 22.8, 22. , 13.9,
       17.9, 18. , 10.9])

In [57]:
print(utils.multiclass.type_of_target(y_train.astype(int)))

multiclass


In [58]:
knn_clf.fit(X_train,y_train.astype(int))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [59]:
knn_clf.score(X_test_standard,y_test.astype(int))

0.0196078431372549

In [63]:
y_test=y_test.astype(int)
y_train=y_train.astype(int)

In [64]:
best_method=""
best_score=0.0
best_k=-1
for method in ["uniform","distance"]:
    for k in range(1,11):
        knn_clf=KNeighborsClassifier(n_neighbors=k,weights=method)
        knn_clf.fit(X_train,y_train)
        score=knn_clf.score(X_test,y_test)
        if score>best_score:
            best_k=k
            best_score=score
            best_method=method
print("best_k=",best_k)
print("best_score=",best_score)
print("best_method=",best_method)

best_k= 1
best_score= 0.0392156862745098
best_method= uniform


In [65]:
%%time
best_p=-1
best_method=""
best_score=0.0
best_k=-1


for k in range(1,11):
    for p in range(1,6):
        knn_clf=KNeighborsClassifier(n_neighbors=k,weights="distance",p=p)
        knn_clf.fit(X_train,y_train)
        score=knn_clf.score(X_test,y_test)
        if score>best_score:
            best_k=k
            best_score=score
            best_p=p
print("best_k=",best_k)
print("best_score=",best_score)
print("best_p=",p)

best_k= 1
best_score= 0.049019607843137254
best_p= 5
CPU times: user 596 ms, sys: 3.81 ms, total: 600 ms
Wall time: 603 ms
